global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'valorant-sim-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    metric_relabel_configs:
      # Add more specific relabeling rules if needed
      - source_labels: [__name__]
        regex: 'app_.*'
        action: keep

  # Frontend application metrics
  - job_name: 'valorant-sim-frontend'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']  # Frontend metrics are proxied through the API
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'app_frontend_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'app_component_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'app_franchise_.*'
        action: keep

  # Add node-exporter for host metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 