global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'valorant-sim-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  # Add node-exporter for host metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 